spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/gm_springboot_layui?useUnicode=true&characterEncoding=UTF-8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: root
      password: root
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    prefix: classpath:/templates
    suffix: .html
    cache: false
    check-template-location: true
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
#  redis:
#    host: 119.23.211.214
#    port: 443
#    password: king123
#    jedis:
#      pool:
#        max-active: 100
#        max-idle: 10
#        max-wait: 100000
#    timeout: 5000
#    database: 0

mybatis:
  type-aliases-package: com.wzj.springboot.dao.mapper
  mapper-locations: classpath:mapper/*.xml


#logging:
#  level:
#    com:
#      wzj:
#        dao: debug

#shiro:
#  loginUrl: /login
#  userNativeSessionManager: true

