spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/permission_example?allowMultiQueries=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      initial-size: 5
      max-idle: 10
      min-idle: 5
      max-wait: 10000
      max-active: 20
      test-on-borrow: true
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    prefix: classpath:/templates
    suffix: .html
    cache: false
    check-template-location: true
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
#  redis:
#    host: 119.23.211.214e
#    port: 443
#    password: king123
#    jedis:
#      pool:
#        max-active: 100
#        max-idle: 10
#        max-wait: 100000
#    timeout: 5000
#    database: 0

mybatis:
  type-aliases-package: com.wzj.springboot.dao.mapper
  mapper-locations: classpath:mapper/*.xml
#server:
#  port: 8080


#logging:
#  level:
#    com:
#      wzj:
#        dao: debug
shiro:
  loginUrl: /admin/jumpLogin
  userNativeSessionManager: true

